FROM golang:1.26-alpine AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -o bcrypt .

FROM busybox:1.37
RUN mkdir -p /usr/local/share/busybox \
    && echo "/bin/busybox sh" > /usr/local/share/busybox/sh \
    && chmod +x /usr/local/share/busybox/sh
RUN addgroup -S bcrypt && adduser -S bcrypt -G bcrypt -s /usr/local/share/busybox/sh
COPY --from=builder /src/bcrypt /bcrypt
USER bcrypt
VOLUME /home/bcrypt
ENTRYPOINT ["/bcrypt"]
